name: pr-merged
on:
  pull_request_target:
    types: [closed]
    branches:
    - 'main'
    paths-ignore:
      - '**.md' ### Ignore running when README.MD changed.
      - '**.yaml' ### Ignore running when YAML files changed.
      - '.github/workflows/*' ### Ignore running when files under path: .github/workflows/* changed.

jobs:
  pr-merged:
    if: ${{ github.event.pull_request.merged == true }}
    permissions:
      id-token: write
      packages: write
      contents: read
      pull-requests: read
    uses: kubescape/workflows/.github/workflows/incluster-comp-pr-merged.yaml@main
    with:
      IMAGE_NAME: quay.io/${{ github.repository_owner }}/prometheus-exporter
      IMAGE_TAG: v0.0.${{ github.run_number }}
      COMPONENT_NAME: prometheus-exporter
      CGO_ENABLED: 0
      GO111MODULE: "on"
      BUILD_PLATFORM: linux/amd64,linux/arm64
      GO_VERSION: "1.22"
      REQUIRED_TESTS: '[]'
      COSIGN: true
      HELM_E2E_TEST: true
    secrets: inherit
